apiVersion: v1
kind: Namespace
metadata:
  name: log

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic
  namespace: log
spec:
  selector:
    matchLabels:
      app: elastic
  replicas: 1
  template:
    metadata:
      labels:
        app: elastic
    spec:
      containers:
        - name: elastic
          image: 'harbor.base-fx.com/itd/elasticsearch:6.8.2'
          ports:
            - containerPort: 9200
              protocol: TCP
            - containerPort: 9300
              protocol: TCP
          env:
            - name: TZ
              value: "Asia/Shanghai"
            - name: "discovery.type"
              value: "single-node"
            - name: node.name
              value: "${HOSTNAME}"
            - name: "cluster.name"
              value: "graylog"
            - name: http.host
              value: 0.0.0.0
            - name: transport.host
              value: localhost
            - name: network.host
              value: 0.0.0.0
            - name: ES_JAVA_OPTS
              value: "-Xms1024m -Xmx6144m"
          volumeMounts:
            - name: storage-elastic
              mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: storage-elastic
          hostPath:
            path: /sw/systems/shared/graylog02/elasticsearch

---

apiVersion: v1
kind: Service
metadata:
  name: elastic-port
  namespace: log
spec:
  type: NodePort
  selector:
    app: elastic
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
      nodePort: 30001
      name: elasticsearch-api
    - protocol: TCP
      port: 9300
      targetPort: 9300
      nodePort: 30002
      name: elasticsearch-client
