version: '3.3'

services:

  opencue-cuebot:
    image: harbor.base-fx.com/itd/opencue/cuebot:latest
    restart: always
    container_name: cue-cuebot
    ports:
      - 8080:8080
      - 8443:8443
    command: --datasource.cue-data-source.jdbc-url=jdbc:postgresql://cue.base-fx.com/cuebot --datasource.cue-data-source.username=postgres --datasource.cue-data-source.password=postgres_cue


  opencue-rqd:
    image: harbor.base-fx.com/itd/opencue/rqd:latest
    restart: always
    container_name: cue-rqd
    environment:
      CUEBOT_HOSTNAME: cue.base-fx.com
    depends_on:
      - opencue-cuebot
    links:
      - opencue-cuebot
    volumes:
      - /opencue/shots:/shots
      - /tmp/rqd/logs:/tmp/rqd/logs
      - /tmp/rqd/shots:/tmp/rqd/shots
    ports:
      - 8444:8444
  
  
