version: '3.3'

services:

  db:
    image: harbor.base-fx.com/itd/postgre:9.6
    restart: always
    container_name: cue-pg
    environment:
      POSTGRES_DB: cuebot
      POSTGRES_PASSWORD: postgres_cue
    ports:
      - 5432:5432
    volumes:
      - /opencue/pgsql-data:/var/lib/postgresql/data

  adminer:
    image: harbor.base-fx.com/itd/adminer:latest
    restart: always
    container_name: cue-pg-mgt
    ports:
      - 8000:8080
  
  
