
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: log
spec:
  selector:
    matchLabels:
      app: kibana
  replicas: 1
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: 'harbor.base-fx.com/itd/kibana:6.8.2'
          ports:
            - containerPort: 5601
              protocol: TCP
          env:
            - name: "TZ"
              value: "Asia/Shanghai"
            - name: "ELASTICSEARCH_HOSTS"
              value: "http://elastic-port:9200"
            - name: "I18N_LOCALE"
              value: "zh-CN"
            - name: "SERVER_NAME"
              value: "kibana"
      #     volumeMounts:
      #       - name: storage-kibana
      #         mountPath: /usr/share/graylog/data/journal
      # volumes:
      #   - name: storage-kibana
      #     hostPath:
      #       path: /sw/systems/shared/graylog02/kibana

---

apiVersion: v1
kind: Service
metadata:
  name: kibana-svc
  namespace: log
spec:
  type: NodePort
  selector:
    app: kibana
  ports:
    - protocol: TCP
      port: 5601
      targetPort: 5601
      nodePort: 30004
