version: "3.1"

services:
    zabbix-server-mysql:
        image: harbor.base-fx.com/itd/zabbix-server-mysql:centos-5.0.2
        restart: unless-stopped
        container_name: zabbix-server-mysql
        environment:
            TZ: "Asia/Shanghai"
            DB_SERVER_HOST: "docker05.base-fx.com"
            DB_SERVER_PORT: "3306"
            MYSQL_USER: "zabbix"
            MYSQL_PASSWORD: "basefx12"
            MYSQL_DATABASE: "zabbix"
        volumes:
            - /docker_data/zabbix/alertscripts:/usr/lib/zabbix/alertscripts
            - /docker_data/zabbix/externalscripts:/usr/lib/zabbix/externalscripts
            - /docker_data/zabbix/modules:/var/lib/zabbix/modules
        ports:
            - "10051:10051"

    zabbix-web:
        image: harbor.base-fx.com/itd/zabbix-web-apache-mysql:centos-5.0.2
        restart: unless-stopped
        container_name: zabbix-web
        environment:
            TZ: "Asia/Shanghai"
            DB_SERVER_HOST: "docker05.base-fx.com"
            DB_SERVER_PORT: "3306"
            MYSQL_USER: "zabbix"
            MYSQL_PASSWORD: "basefx12"
            MYSQL_DATABASE: "zabbix"
            ZBX_SERVER_HOST: "zabbix-server-mysql"
            PHP_TZ: "Asia/Shanghai"
            ZBX_SERVER_NAME: ""
            ZBX_MEMORYLIMIT: "1024M"
        ports:
            - "8080:8080"
            - "8443:8443"

