global:
  smtp_smarthost: 'internal-smtp.base-fx.com:25'
  smtp_from: 'prometheus@base-fx.com'
  smtp_require_tls: false
  smtp_hello: 'alertmanager'

# templates:

route:
  receiver: 'test'
  group_by: ['BJ','mysql']   #报警分组依据
  group_wait: 30s # 最初即第一次等待多久时间发送一组警报的通知
  group_interval: 1m   # 在发送新警报前的等待时间
  repeat_interval: 4h   # 发送重复警报的周期，对于email配置中，此项不可以设置过低，否则将会由于邮件发送频繁，被smtp服务器拒绝

receivers:
- name: 'itdbj'
  email_configs:
  - to: 'itdbj@base-fx.com'

- name: 'test'
  email_configs:
  - to: 'zhangyt@base-fx.com'
