apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment01
spec:
  selector:
    matchLabels:
      app: nginx-deployment01
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-deployment01
    spec:
      containers:
      - name: nginx
        image: harbor.base-fx.com/itd/nginx:stable
        imagePullPolicy: Always
        ports:
          - containerPort: 80
            protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment01-port
spec:
    type: NodePort
    selector:
      app: nginx-deployment01
    ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
