version: '3.3'

services:
  graylog-mongo:
    image: harbor.base-fx.com/common/mongo:4.2.0
    container_name: graylog-mongo
    restart: unless-stopped
    environment:
      TZ: "Asia/Shanghai"
    volumes: 
      - graylog_mongo:/data/db

    ports:
      - "27017:27017"

  graylog-elastic:
    image: harbor.base-fx.com/common/elasticsearch:6.8.2
    container_name: graylog-elastic
    restart: unless-stopped
    environment:
      discovery.type: 'single-node'
      cluster.name: 'graylog'
      http.host: '0.0.0.0'
      transport.host: 'localhost'
      network.host: '0.0.0.0'
      ES_JAVA_OPTS: '-Xms512m -Xmx512m'
      TZ: "Asia/Shanghai"
    volumes: 
      - graylog_elastic:/usr/share/elasticsearch/data
    # ports:
    #   - "9200:9200"
    #   - "9300:9300"

  graylog-server:
    image: harbor.base-fx.com/common/graylog:3.1.0
    container_name: graylog-server
    restart: unless-stopped
    links:
      - graylog-mongo:mongo
      - graylog-elastic:elasticsearch
    depends_on:
      - graylog-mongo
      - graylog-elastic
    environment:
      GRAYLOG_HTTP_EXTERNAL_URI: 'http://10.14.7.21:9000/'
      # GRAYLOG_MONGODB_URI=mongodb://graylog-mongo/graylog
      # GRAYLOG_ELASTICSEARCH_HOSTS=http://graylog-elastic:9200
      GRAYLOG_ROOT_TIMEZONE: 'Asia/Shanghai'
      GRAYLOG_ROOT_USERNAME: 'admin'
      #密码需要填写 SHA256 加密的密文，例如这里是 admin
      GRAYLOG_ROOT_PASSWORD_SHA2: '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918'
      GRAYLOG_PASSWORD_SECRET: 'somepasswordpepper'
      TZ: "Asia/Shanghai"
    volumes: 
      - graylog_data:/usr/share/graylog/data/journal
    ports:
      - 9000:9000
      - 12201:12201
      - 1514:1514
      - 12201:12201/udp
      - 1514:1514/udp

volumes:
  graylog_mongo: 
    driver_opts:
      type: "nfs"
      o: "addr=10.14.6.159,rw,nolock,intr"
      device: ":/mydata/docker_nfs/graylog/mongodb"
  graylog_elastic: 
    driver_opts:
      type: "nfs"
      o: "addr=10.14.6.159,rw,nolock,intr"
      device: ":/mydata/docker_nfs/graylog/elastic"
  graylog_data: 
    driver_opts:
      type: "nfs"
      o: "addr=10.14.6.159,rw,nolock,intr"
      device: ":/mydata/docker_nfs/graylog/data"
