version: "3.1"

services:
    db:
        image: harbor.base-fx.com/itd/mariadb:10.4
        restart: unless-stopped
        container_name: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: mysql325
            TZ: "Asia/Shanghai"
        volumes:
            - /docker_data/mariadb/data:/var/lib/mysql
            - /docker_data/mariadb/etc:/etc/mysql/mariadb.conf.d
        ports:
            - "3306:3306"
